package com.tcs.plts.common.enums;

public enum OrderStatus {
    CREATED,
    MANUFACTURER_ASSIGNED,
    MANUFACTURING,
    MANUFACTURING_COMPLETED,
    QA_ASSIGNED,
    QA_IN_PROGRESS,
    QA_COMPLETED,
    PACKAGING_ASSIGNED,
    PACKAGING_IN_PROGRESS,
    PACKAGING_COMPLETED,
    TRANSPORT_COMPLETED,
    RETAILER_ASSIGNED,
    DELIVERED,
    COMPLETED,
    REJECTED
}
